/*
CLIENT - ANGULAR, REACT, VUE, VENILA
SERVER - NODE JS, EXPRESS JS

MERN MEAN FULL STACK
*/
// variables let, const, var

let name1 = 'massmind'; // mutable/ changeable
const name2 = 'massmind'; // immutable
var name = 'massmind'; // mutable/ changeable - deprecated

// data structure:

let name4;

name4="massmind"

// const name = 'massmind'; //string

const age = 30; //number

const status = false //boolean either true or false

const object = {
    // name: "massmind",
    age: 10,
    status: true,
    address:{
        line1: 'werw',
        pin: '98798734'
    }
} //ordered collection

const arr = ['massmind', 30, false, true, {test: 'demo_test'}] //unordered collection

undefined
null
// symbol

//___________________________________

console.log('Hello world')
console.log('I am learning Js')

const myAge = {names: 'test'};
console.log(myAge)
console.log(typeof myAge)

// For checking types use 'typeof'

